name: Vercel Preview Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: ["main", "staged"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check conditions
        id: check
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.base_ref }}" == "staged" && "${{ github.event.pull_request.title }}" == *"[deploy]"* ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Vercel
        if: steps.check.outputs.deploy == 'true'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
